spring.application.name=ClassManagement
spring.datasource.url=jdbc:mysql://localhost:3306/ClassManagement
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update